name: phyclone
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.12
  - llvmdev
  - click>=8.3
  - networkx>=3.6.1
  - rustworkx>=0.15.1
  - numba>=0.61.2
  - numpy>=2.0.0
  - pandas>=2.2.2
  - scipy
  - python-xxhash>=3.3.0
  - h5py
